### ISSUE TITLE
A Longshot: Final Updates?

### ISSUE THREAD

**Issue by buckeyede06** [BSData/battlefleetgothic#10]
Anyone want to finalize all the lists on a defunct game?! I know people who still play. Eldar and Orks would be huge.

**Comment by Tomakokamikaze** [comment]
I would like to finish it. Im still learning how though.

**Comment by buckeyede06** [comment]
It would be amazing!

On Feb 6, 2018, at 11:24 AM, Marco Antonio <notifications@github.com<mailto:notifications@github.com>> wrote:


I would like to finish it. Im still learning how though.

**Comment by Tomakokamikaze** [comment]
i am on it now =)

**Comment by buckeyede06** [comment]
Nice! Any interest in working on the other factions too? Eldar, CE Eldar, Ork, etc

**Comment by Tomakokamikaze** [comment]
As soon as I can, Im doing Orks now, if you can create Issues with what needs to be fixed, that would help me a lot.

**Comment by buckeyede06** [comment]
They are basically all empty. But I can log point value or errors once up. For instance the point values have changed with the latest rule updates under BFG 2002 Annual.

On Feb 25, 2018, at 3:07 PM, Marco Antonio <notifications@github.com<mailto:notifications@github.com>> wrote:


As soon as I can, Im doing Orks now, if you can create Issues with what needs to be fixed, that would help me a lot.
