### ISSUE TITLE
Release title marketing

### ISSUE THREAD

**Issue by amis92** [BSData/battlefleetgothic#111]
Hi @Mont-Fox 

Let me start by an appreciation remark. Your work in this dataset is undeniably impactful. The game community surely is thankful for that. We, BSData admins are also grateful for your work and effort.

However, out of 14 releases from last 3 weeks (since you started), you've linked and attributed the work to DnDTonight.com directly within release title in 13 of them. Now, we do not have any binding rules you broke. We're all a gathering of people who mostly keep their scope to a single game system they take care of, under a common "brand" of BSData.

We have discussed the issue of the release titles in this repository, and feel that this is not in line of the community spirit we want to groom here. There are some of us that have personal projects (which DnDTonight.com seems to be for you), but we refrain for advertising them via release titles, or any other channels associated with BSData.

We'd like you to no longer advertise your hobby project via release titles here on BSData. We hope for your understanding.

Sincerely,
BSData Team

PS We don't have as much control as we'd like to over our social channels, and the net result is that the release titles are all automatically posted to them. Your release titles imply an association between BSData and DnDTonight which is something we're not supportive of.

**Comment by Mont-Fox** [comment]
Alright,

I will correct this in future release titles.

**Comment by amis92** [comment]
Thank you. We have nothing against occasional mention. We're all hobbyists. It just grew a little monotonous. :)
