### ISSUE TITLE
[Anon] Bug report: Tyranid.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/battlefleetgothic#169]
**File:** Tyranid.catz

**BattleScribe version:** 1.11.11

**Platform:** Android

**Dropbox:** No

**Description:** Hi <@247185158032195585>! I've noticed a few oddities in the Tyranid fleet that seemed worth pointing out.
1- Prow torpedoes on Hiveships are firepower 6 when they should be 8.
2- The fireship option for drones from the 2010 update seems to be missing. Is that deliberate?
3- Escort squadrons don't quite work as I expected. BS seems to give one escort squadron of any size per Hiveship, as opposed to 1-12 escorts in any number of squadrons (plus a mandatory 6 escort drones that can be part of or on top of the 1-12 of any kind). Is that a mistake, or a compromise made with how BS is structured?
4- No Mega Spore Mine biomorph? *sad intergalactic predator noises*

**Comment by Mont-Fox** [comment]
Found another Tyranid issue, Kraken are listed as 5+ armour in the profile rather than 6+
