### ISSUE TITLE
Codex Astartes Fleet List

### ISSUE THREAD

**Issue by Alicks181** [BSData/battlefleetgothic#186]
Units missing:
Venerable battlebarge - battleship

units needs removing:
Falchion frigate- escort

unit incorrectly costed:
Firestorm Frigate- escort. costed at 40pts, should be 45pts for the Rapid Strike Vessle variant

**Comment by Mont-Fox** [comment]
![image](https://user-images.githubusercontent.com/72281213/220222668-4c0b602b-e4bc-40b4-9afe-02ac8d882ce6.png)
no you may not have a venerable battle barge unless you can tell me where it comes from
