### ISSUE TITLE
Ork Waaagh fleet list

### ISSUE THREAD

**Issue by Alicks181** [BSData/battlefleetgothic#189]
units that need removing: 
lite kroozer- cruiser 

upgrade to add in:
Hammer Class battlekroozer needs Dakka Dakka upgrade option, this in a separate option to its +1 turret  upgrade 
![Screenshot_20230130_215615_Drive](https://user-images.githubusercontent.com/123834062/215604284-e365986f-92a7-4f0a-876e-a27300ecd9e2.jpg)

**Comment by Mont-Fox** [comment]
![image](https://user-images.githubusercontent.com/72281213/220222117-921697b6-3c26-4ec2-9d1a-bd4f8ee92665.png)

**Comment by Mont-Fox** [comment]
lite kroozer is gone and dakka dakka doesn't apply
