### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by EternalWIP** [BSData/battlefleetgothic#218]
Want to fix up some armour values, generally tidy up some stat lines (missing measurements and the like), hopefully get around to adding in missing ships (Scion of Prospero, Wage of Sin) and then anything else that comes to mind (adding Gifts of Omnissiah to Arch-Magos for example)

**Comment by Mont-Fox** [comment]
> Want to fix up some armour values, generally tidy up some stat lines (missing measurements and the like), hopefully get around to adding in missing ships (Scion of Prospero, Wage of Sin) and then anything else that comes to mind (adding Gifts of Omnissiah to Arch-Magos for example)

Hiya! Welcome to the team. If you'd like to talk over the BSDATA for gothic my Discord is mont1687
