### ISSUE TITLE
[Anon] Bug report: Abbadons Black Crusade.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/battlefleetgothic#22]
**File:** Abbadons Black Crusade.catz

**BattleScribe version:** 2.01.14

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** The chaos Styx heavy cruiser is 260 as well as the Retaliator grand cruiser. According to the latest BFG 2010 FAQ

**Comment by Tomakokamikaze** [comment]
Those Cruisers are already costing that much. have you tried deleting your data files and downloading the new release?
