### ISSUE TITLE
[Anon] Bug report: Abbadons Black Crusade.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/battlefleetgothic#28]
**File:** Abbadons Black Crusade.catz

**BattleScribe version:** 2.01.14

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Capital ship restrictions 1 battleship to every 3 cruisers or heavy cruisers, 1 gran cruiser to every 3 cruiser or heavy cruiser, 1 heavy to every cruiser, 0-12 cruisers.

**Comment by Tomakokamikaze** [comment]
Finaly solved it the new Rosters from Amis92
