### ISSUE TITLE
[Anon] Bug report: Imperial Gothic.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/battlefleetgothic#34]
**File:** Imperial Gothic.catz

**BattleScribe version:** 2.01.20

**Platform:** Android

**Dropbox:** No

**Description:** Any new roster created for this always starts with a Cobra Escort and will produce the orange exclamation point if the roster doesn't contain one, despite the presence of any records being non-mandatory.

**Comment by Tomakokamikaze** [comment]
fixed
