### ISSUE TITLE
Missing FAQ info.

### ISSUE THREAD

**Issue by hobodabobo** [BSData/battlefleetgothic#4]
I don't know if this is wanted or not, but the fleet list is missing the updates from the 2010 FAQ. Just a suggestion, as it modifies point costs of escorts, and a few other things.

**Comment by amis92** [comment]
As you can see, there is not much going on here - last update was 8 months ago. If you want to update files, feel free to fork and make pull request. Or maybe @Itsacon will happen to respond - he's the latest author here.

**Comment by Itsacon** [comment]
I don't mind having a look at it, but that will be next month at the soonest. @hobodabobo, if you want to have a look at it yourself, feel free. Otherwise I'll put it on my to-do list for April.

**Comment by hobodabobo** [comment]
Thanks. It was just an observation. I'm really rusty at best with battle scribe files, so that's why I thought I'd check on here.

**Comment by carlisimo** [comment]
I created a patch with a few points changes, but that wouldn't cover the 2010 FAQ changes.  As I figure out this script I'll see if I can go through the other FAQ changes - torpedo bommas, gubbins, clan upgrades, and a new ship type or two (or 3, it looks like).

**Comment by Tomakokamikaze** [comment]
I did some changes to the chaos roster but if you have anything to add, please make a pull request and I will approve it.

**Comment by Tomakokamikaze** [comment]
If anyone else has a FAQ update or Magazine source ship they would like to see added just make an issue.
see yall later.
