### ISSUE TITLE
New Force Org: Heresy Fleets

### ISSUE THREAD

**Issue by zzihm** [BSData/battlefleetgothic#40]
I'm working on a Heresy-era fleet list based on a [fairly popular homebrew rule set](https://www.dropbox.com/sh/uemue72c1pcaof4/AAALhqJUhKOy7rDNei2Bjt7xa/Specialist%20Games/Battle%20Fleet%20Heresy/3rd%20Ed.%20Rules?dl=0&preview=Heresy%20Fleet%20List%203rd%20Ed..pdf&subfolder_nav_tracking=1&fbclid=IwAR28bNF7PiukT1ZyKuRqMBJgmJajSg2izrvj_Zeml0JtcNPHJ28qcnyl7_E) (not my rules). I have a working version ready and would love to share it if I can.

**Comment by Tomakokamikaze** [comment]
Alright then, lets see it

**Comment by zzihm** [comment]
Done!

**Comment by Tomakokamikaze** [comment]
Its merged, I will make a release, and it should be up tomorrow morning (12hrs from now I think)

**Comment by Tomakokamikaze** [comment]
All done, pleasure doing business with you mate. if you wanna upgrade/change anything, just let me know.
