### ISSUE TITLE
[Anon] Bug report: Space Marines Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/battlefleetgothic#5]
**File:** Space Marines Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** No option to select named psykers like Severn loth or Mepheston when you select the librarius conclave

**Comment by Tomakokamikaze** [comment]
I think you are in the wrong game friend, I havent found any sign of psykers in the Battlefleet Gothic Rules. could you please tell me where you read them?
