### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Mont-Fox** [BSData/battlefleetgothic#57]
I'm new to this whole data repository thing, but I'd like to clean up the battlefleet gothic stuff so that it's consistent across fleets.

**Comment by amis92** [comment]
/invite

Hi @Mont-Fox - maybe start with reviewing #48 and merging it if it's ok - the PR author has already contributed here a lot, so I'd guess it's good.

**Comment by Mont-Fox** [comment]
> /invite
> 
> Hi @Mont-Fox - maybe start with reviewing #48 and merging it if it's ok - the PR author has already contributed here a lot, so I'd guess it's good.
> 
> [Workflow run](https://github.com/BSData/chatops/actions/runs/285021629)
> 🤖 Invited @Mont-Fox with **push** access. Invite can be accepted on https://github.com/BSData/battlefleetgothic/invitations

Do I have access to be able to merge this. I'm trying to follow the youtube video but it doesn't quite look the same.
