### ISSUE TITLE
Need write access to BSData/battlefleetgothic

### ISSUE THREAD

**Issue by Mont-Fox** [BSData/battlefleetgothic#60]
I would like to be added to the BSData gothic code owners so that I may release changes.

**Comment by amis92** [comment]
Please read carefully: https://github.com/BSData/battlefleetgothic/issues/57#issuecomment-702974215

**Comment by amis92** [comment]
@Mont-Fox in the link above there's an original invitation comment. It has all necessary info and links.

**Comment by Mont-Fox** [comment]
Found the link thanks!
