### ISSUE TITLE
[Anon] Bug report: Adeptus Mechanicum.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/battlefleetgothic#7]
**File:** Adeptus Mechanicum.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** Yes

**Description:** When I try to create a AM list I get the following message:
There were some problems with your data files. If you continue, this may lead to crashes and other strange behavior.

> Adeptus Mechanicus Fleet List v2:
> The catalogue data file is invalid:
> Ark Mechanicus Omnissiah's Victory (415pts): Entry must have a category that exists
> Defiant Light Cruiser (130pts): Entry must have a category that exists
> This continues for all the other entries ....

**Comment by Tomakokamikaze** [comment]
Well, i havent had this problem,. are you still having this issue?
