### ISSUE TITLE
[Anon] Bug report: Space Marines Crusade.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/battlefleetgothic#9]
**File:** Space Marines Crusade.catz

**BattleScribe version:** 2.01.01

**Platform:** Android

**Dropbox:** No

**Description:** I downloaded battles scrib (latest mode)and became a member. And downloaded battlefleet Gothic. But it won't open. Could use some advice. Thanks.

**Comment by Tomakokamikaze** [comment]
are you still having any issues?
