### ISSUE TITLE
[Anon] Bug report: Necron.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/battlefleetgothic#99]
**File:** Necron.catz

**BattleScribe version:** 1.11.11

**Platform:** Android

**Dropbox:** No

**Description:** Need portal rules. Need lightning arc rules and partical whip.rules 
The tombship has the requirements listed on profile. May be good to copy into other fleets for validation

**Comment by Mont-Fox** [comment]
closed in PR#113
